### ISSUE TITLE
Doesn't seem to work on Windows 11

### ISSUE THREAD

**Issue by InfectedAnimal** [kythyria/payday2-model-tool#24]
I've been trying to use this program for the past day but each time I do it does the cursor loading animation and then promptly does nothing, not even giving an error or warning message, please fix this

**Comment by Sprixitite** [comment]
Hi! I'm a linux user, but this problem sounds interesting, if you could give some debug info (I believe the console has been re-revealed on the newest commit) I would love to take a stab at this regardless. Thanks.

**Comment by ghost** [comment]
I'm also on Windows 11 and can confirm it does not launch properly (I see the console window for a second or two and then it closes without warning), here is what the console spits out from the latest commit:
```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Windows.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Windows.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at PD2ModelParser.Program.Main(String[] args)

```

**Comment by Sprixitite** [comment]
Thanks for the message, as the notification reminded me I had set up a windows 11 VM to work on this before deleting it, although looking at your error it seems to be a simple fix to the PD2ModelParser.csproj file

Going to test if my changes regress anything to do with the non-windows pre-build events this project has and if they don't will submit a pr to hopefully resolve this!

**Comment by ghost** [comment]
still getting the error with the new ver D:

```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Windows.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Windows.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at PD2ModelParser.Program.Main(String[] args)
```

**Comment by InfectedAnimal** [comment]
> still getting the error with the new ver D:
> 
> 
> 
> ```
> 
> Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Windows.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
> 
> File name: 'System.Windows.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
> 
>    at PD2ModelParser.Program.Main(String[] args)
> 
> ```
> 
> 
> 
> 

Can confirm this here too, tried the patched build recently and it'd still close each time very briefly displaying this error
![image](https://user-images.githubusercontent.com/92275331/223192549-2f07c894-59ec-4eb0-b2fe-1237533b2d4d.png)

**Comment by Sprixitite** [comment]
See [my PR](https://github.com/kythyria/payday2-model-tool/pull/26) for what is likely the same issue everyone in this thread is seeing

If it doesn't resolve the issue then please send further details, but I'd imagine what most of you are seeing is simply a missing .net 6 runtime

Something additional to note: you likely haven't even tried the slightly patched version, because the PR has yet to be accepted and added to the release page

**Comment by kythyria** [comment]
Y'all try the newest build now I've actually merged that PR.

**Comment by InfectedAnimal** [comment]
> See [my PR](https://github.com/kythyria/payday2-model-tool/pull/26) for what is likely the same issue everyone in this thread is seeing
> 
> If it doesn't resolve the issue then please send further details, but I'd imagine what most of you are seeing is simply a missing .net 6 runtime
> 
> Something additional to note: you likely haven't even tried the slightly patched version, because the PR has yet to be accepted and added to the release page

Yea I just downloaded it and it finally works, was a bit confused on the lack of exe with it but I used the og one and it finally worked

Thank you so much
